### ISSUE TITLE
[Feature request] Add timestamp to Time Outs

### ISSUE THREAD

**Issue by TitusEntertainment** [mrjvs/designcourse-bot#1]
Please, add a timestamp to the timeout event.

Reason:

This way we can investigate further and perhaps change the values so that we can optimize the waiting period for the user among other things.

<img width="429" alt="image" src="https://user-images.githubusercontent.com/16852656/88386754-5956fd00-cdb1-11ea-8813-c45b70f05d85.png">

**Comment by mrjvs** [comment]
https://i.imgur.com/010lHNG.png done
